server:
   port: 80

spring:
   application:
      name: zuul-server
  
   redis:
      database: 0
      host: 192.168.99.100
      prot: 6379
      password:
      timeout: 5000
      jedis:
         pool:
            max-active: 8

zuul:
   # 开始重试机制
   retryable: true
   # 所有服务的敏感头不都过滤
   sensitive-headers: 
   max:
      host:
         connections: 500
   host:
      # 最大连接数，默认是200
      max-total-connections: 200
      # 每个路由的最大连接数， 默认是20
      max-per-route-connections: 20
   routes:
      # 写一个标识你服务的名称
      service-rpc-user:
         path: /user/**
         service-id: user-server
         
      service-rpc-product:
         path: /product/**
         service-id: product-server
         
      # 上面的缩写方式就是  服务器名: 拦截路径
      order-server: /order/**

hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 6000

eureka:
   client:
      service-url:
         defaultZone: http://navy:123321@127.0.0.1:6611/eureka

#logging:
#   level:
#      root: debug