spring:
   profiles:
      active: dev-6622

---
server:
   port: 6622

spring:
   profiles: dev-6622
   application:
      name: config-server
   cloud:
      config:
         server:
            git:
               uri: https://gitee.com/navy-zhou/snack-config
               username: haijunzhou@hnit.edu.cn
               password: navy123321,.
               # 默认读取的分支，默认就是master
               default-label: master
               # 配置文件自动下载后的保存路径
               basedir: D:\\workspaces\\basedir
               # 启动的时候从git获取配置文件到本地
               clone-on-start: true
               force-pull: true
      bus:
         enabled: true
         trace:
           enabled: true
           
   rabbitmq:
      host: 192.168.99.100
      port: 5672
      username: guest
      passwor: guest
      
management:
   endpoints:
      web:
         exposure:
            # 需要开启对外的请求地址
            include: bus-refresh  
                         
eureka:
   client:
      service-url:
         defaultZone: http://navy:123321@127.0.0.1:6611/eureka
               
               